name: Security Analysis (zizmor)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read # Required to read the code for analysis

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security-analysis:
    name: Run Zizmor Security Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required to create security events from the analysis results
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Run zizmor security analysis
        uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054 # v0.6.2
        with:
          inputs: .github/workflows/*.yml # Don't specify just the folder. Otherwise, it won't load the preview in the results
          token: ${{ secrets.GITHUB_TOKEN }}
          min-severity: low
          min-confidence: low
          persona: auditor