name: Security Analysis (zizmor)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read # Required to read the code for analysis

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security-analysis:
    name: Run Zizmor Security Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required to create security events from the analysis results
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Run zizmor security analysis
        uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7
        with:
          inputs: .github/workflows/*.yml # Don't specify just the folder. Otherwise, it won't load the preview in the results
          token: ${{ secrets.GITHUB_TOKEN }}
          min-severity: low
          min-confidence: low
          persona: auditor